site_name: Beamline
edit_uri: ""

nav:
  - Introduction:
      - intro/beamline-framework.md
      - intro/streaming-process-mining.md
      - intro/installation.md
      - intro/pybeamline-designer.md
      - intro/basic-concepts.md
  - pyBeamline doc:
    - pybeamline/index.md
    - pybeamline/basic-concepts.md
    - pybeamline/sources-sinks/
  - JBeamline doc:
    - Getting started: jbeamline/index.md
    - Implemented techniques:
      - Control-flow discovery:
        - Trivial Miner:                jbeamline/implemented-techniques/discovery-trivial.md
        - Heuristics Miner:             jbeamline/implemented-techniques/discovery-heuristics-miner.md
        - Declare Miner:                jbeamline/implemented-techniques/discovery-declare.md
        - DCR Miner:                    jbeamline/implemented-techniques/discovery-dcr.md
        - Soft Conformance Model Miner: jbeamline/implemented-techniques/discovery-soft.md
        - Split Miner:                  jbeamline/implemented-techniques/discovery-splitminer.md
      - Conformance checking:
        - Behavioural Patterns:         jbeamline/implemented-techniques/conformance-behavioural-patterns.md
        - Soft Conformance:             jbeamline/implemented-techniques/conformance-soft.md
      - Simulation:
        - Simulation with PLG:          jbeamline/implemented-techniques/simulation-plg.md
    - Examples:
        - Introduction:                                      examples/index.md
        - pyBeamline:
          - pyBeamline full cycle:                           examples/pybeamline/full-cycle.md
        - Beamline:
          - Raw data as input (non-process mining ready):    examples/beamline/no-process-mining-as-input.md
          - Monitoring active windows (for Windows systems): examples/beamline/monitoring-windows.md
          - Speech recognition:                              examples/beamline/speech-recognition.md
          - Wikipedia edits:                                 examples/beamline/wikipedia-edits.md
          - OpenSky monitoring:                              examples/beamline/open-sky-monitoring.md
    - Additional libraries:
        - MQTT-XES:                     beamline/mqtt-xes.md
        - Simple PNML:                  beamline/simple-pnml.md

  - About: about.md

theme:
  name: material
  logo: img/logo.svg
  palette:
    primary: default
  font:
    text: Fira Sans
    code: Fira Code


  features:
  - navigation.tabs
  - navigation.tabs.sticky
  # - navigation.expand
  # - navigation.indexes
  # - toc.integrate
  - content.code.copy

repo_name: beamline/pybeamline
repo_url: https://github.com/beamline/pybeamline

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid@8.13.5/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes

copyright: Copyright &copy; 2022-2026 Technical University of Denmark
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beamline

