site_name: Beamline
edit_uri: ""

nav:
  - Home: index.md
  - pyBeamline: pybeamline.md
  - Beamline:
    - Getting started: beamline/index.md
    - Implemented techniques:
      - Control-flow discovery:
        - Trivial Miner:                beamline/implemented-techniques/discovery-trivial.md
        - Heuristics Miner:             beamline/implemented-techniques/discovery-heuristics-miner.md
        - Declare Miner:                beamline/implemented-techniques/discovery-declare.md
        - DCR Miner:                    beamline/implemented-techniques/discovery-dcr.md
        - Soft Conformance Model Miner: beamline/implemented-techniques/discovery-soft.md
        - Split Miner:                  beamline/implemented-techniques/discovery-splitminer.md
      - Conformance checking:
        - Behavioural Patterns:         beamline/implemented-techniques/conformance-behavioural-patterns.md
        - Soft Conformance:             beamline/implemented-techniques/conformance-soft.md
      - Simulation:
        - Simulation with PLG:          beamline/implemented-techniques/simulation-plg.md
    - Additional libraries:
        - MQTT-XES:                     beamline/mqtt-xes.md
        - Simple PNML:                  beamline/simple-pnml.md
  - Examples:
      - Introduction:                                      examples/index.md
      - pyBeamline:
        - pyBeamline full cycle:                           examples/pybeamline/full-cycle.md
      - Beamline:
        - Raw data as input (non-process mining ready):    examples/beamline/no-process-mining-as-input.md
        - Monitoring active windows (for Windows systems): examples/beamline/monitoring-windows.md
        - Speech recognition:                              examples/beamline/speech-recognition.md
        - Wikipedia edits:                                 examples/beamline/wikipedia-edits.md
        - OpenSky monitoring:                              examples/beamline/open-sky-monitoring.md
  - About: about.md

theme:
  name: material
  logo: img/logo.svg
  palette:
    primary: default

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.expand
  - toc.integrate

repo_url: https://github.com/beamline/pybeamline

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid@8.13.5/dist/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes

copyright: Copyright &copy; 2022-2025 Technical University of Denmark
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beamline

