site_name: Beamline
edit_uri: ""

nav:
  - Introduction:
      - intro/beamline-framework.md
      - intro/streaming-process-mining.md
      - intro/basic-concepts.md
  - pyBeamline doc:
    - pybeamline/index.md
    - pybeamline/installation.md
    - pybeamline/basic-concepts.md
    - pybeamline/pybeamline-designer.md
    - Examples:
      - pybeamline/examples/full-cycle.md
  - JBeamline doc:
    - jbeamline/index.md
    - jbeamline/installation.md
    - jbeamline/basic-concepts.md
    - Control-flow discovery:
      - jbeamline/implemented-techniques/discovery-trivial.md
      - jbeamline/implemented-techniques/discovery-heuristics-miner.md
      - jbeamline/implemented-techniques/discovery-declare.md
      - jbeamline/implemented-techniques/discovery-dcr.md
      - jbeamline/implemented-techniques/discovery-soft.md
      - jbeamline/implemented-techniques/discovery-splitminer.md
    - Conformance checking:
      - jbeamline/implemented-techniques/conformance-behavioural-patterns.md
      - jbeamline/implemented-techniques/conformance-soft.md
    - Simulation:
      - jbeamline/implemented-techniques/simulation-plg.md
    - Examples:
      - jbeamline/examples/no-process-mining-as-input.md
      - jbeamline/examples/monitoring-windows.md
      - jbeamline/examples/speech-recognition.md
      - jbeamline/examples/wikipedia-edits.md
      - jbeamline/examples/open-sky-monitoring.md
    - Additional libraries:
        - jbeamline/mqtt-xes.md
        - jbeamline/simple-pnml.md

  - About: about.md

theme:
  name: material
  logo: img/logo.svg
  palette:
    primary: default
  font:
    text: Fira Sans
    code: Fira Code


  features:
  - navigation.tabs
  - navigation.tabs.sticky
  # - navigation.expand
  # - navigation.indexes
  # - toc.integrate
  - content.code.copy

repo_name: beamline/pybeamline
repo_url: https://github.com/beamline/pybeamline

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid@8.13.5/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes

copyright: Copyright &copy; 2022-2026 Technical University of Denmark
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beamline

